fix: action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,6 +8,21 @@ branding:
 
 inputs:
   #
+  # Common
+  #
+  paths-ignore:
+    description: 'Substring of paths to ignore (like on.push.paths-ignore) but with regex'
+    required: false
+    default: ''  # empty string
+  skip-checkout:
+    description: 'If true, skip the checkout step'
+    required: false
+    default: 'false'
+  debug:
+    description: 'Debug mode'
+    required: false
+    default: 'false'
+  #
   # Push event
   # ref. # https://docs.github.com/ja/webhooks/webhook-events-and-payloads#push
   #
@@ -30,17 +45,6 @@ inputs:
     description: 'The head branch of the pull request (pull_request trigger only)'
     required: false
     default: ${{ github.head_ref }}
-  #
-  # Common
-  #
-  paths-ignore:
-    description: 'trigger GitHub Actions '
-    required: false
-    default: ""
-  debug:
-    description: 'Debug mode'
-    required: false
-    default: "false"
 
 outputs:
   skip:
@@ -48,13 +52,92 @@ outputs:
     description: 'Skip the following steps'
 
 runs:
-  using: 'composite'
+  using: composite
   steps:
-    - uses: actions/checkout@v4
+    - if: ${{ inputs.skip-checkout != 'true' }}
+      uses: actions/checkout@v4
       with:
         fetch-depth: 0
+    - name: github-actions-paths-ignore-alternative
+      id: paths-ignore
+      shell: 'bash'
+      run: |
+        # LICENSE: https://github.com/kunitsucom/log.sh/blob/HEAD/LICENSE
+        # Common
+        if [ "${LOGSH_COLOR:-}" ] || [ -t 2 ] ; then LOGSH_COLOR=true; else LOGSH_COLOR=''; fi
+        _logshRFC3339() { date "+%Y-%m-%dT%H:%M:%S%z" | sed "s/\(..\)$/:\1/"; }
+        _logshCmd() { for a in "$@"; do if echo "${a:-}" | grep -Eq "[[:blank:]]"; then printf "'%s' " "${a:-}"; else printf "%s " "${a:-}"; fi; done | sed "s/ $//"; }
+        # Color
+        LogshDefault() { test "  ${LOGSH_LEVEL:-0}" -gt 000 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;35m}  DEFAULT${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshDebug() { test "    ${LOGSH_LEVEL:-0}" -gt 100 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;34m}    DEBUG${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshInfo() { test "     ${LOGSH_LEVEL:-0}" -gt 200 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;32m}     INFO${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshNotice() { test "   ${LOGSH_LEVEL:-0}" -gt 300 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;36m}   NOTICE${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshWarn() { test "     ${LOGSH_LEVEL:-0}" -gt 400 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;33m}     WARN${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshWarning() { test "  ${LOGSH_LEVEL:-0}" -gt 400 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;33m}  WARNING${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshError() { test "    ${LOGSH_LEVEL:-0}" -gt 500 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;31m}    ERROR${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshCritical() { test " ${LOGSH_LEVEL:-0}" -gt 600 || echo "$*" | awk "{print \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;1;31m} CRITICAL${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshAlert() { test "    ${LOGSH_LEVEL:-0}" -gt 700 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;41m}    ALERT${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshEmergency() { test "${LOGSH_LEVEL:-0}" -gt 800 || echo "$*" | awk "{print \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;1;41m}EMERGENCY${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
+        LogshExec() { LogshInfo "$ $(_logshCmd "$@")" && "$@"; }
+        LogshRun() { _dlm="####R#E#C#D#E#L#I#M#I#T#E#R####" && _all=$({ _out=$("$@") && _rtn=$? || _rtn=$? && printf "\n%s" "${_dlm:?}${_out:-}" && return "${_rtn:-0}"; } 2>&1) && _rtn=$? || _rtn=$? && _dlmno=$(echo "${_all:-}" | sed -n "/${_dlm:?}/=") && _cmd=$(_logshCmd "$@") && _stdout=$(echo "${_all:-}" | tail -n +"${_dlmno:-1}" | sed "s/^${_dlm:?}//") && _stderr=$(echo "${_all:-}" | head -n "${_dlmno:-1}" | grep -v "^${_dlm:?}") && LogshInfo "$ ${_cmd:-}" && LogshInfo "${_stdout:-}" && { [ -z "${_stderr:-}" ] || LogshWarning "${_stderr:?}"; } && return "${_rtn:-0}"; }
+        # export functions for bash
+        # shellcheck disable=SC3045
+        echo "${SHELL-}" | grep -q "/?bash" && export -f _logshRFC3339 _logshCmd LogshDefault LogshDebug LogshInfo LogshWarning LogshError LogshCritical LogshAlert LogshEmergency LogshExec LogshRun || true
+
+        #
+        # inputs
+        #
+        LogshInfo " github.event_name: ${{ github.event_name }}"
+        LogshInfo "     inputs.before: ${{ inputs.before }}"
+        LogshInfo "      inputs.after: ${{ inputs.after }}"
+        LogshInfo "   inputs.base-ref: ${{ inputs.base-ref }}"
+        LogshInfo "   inputs.head-ref: ${{ inputs.head-ref }}"
+
+        #
+        # main
+        #
+        LogshInfo "Create paths-ignore.txt (without comments and empty lines)"
+        grep -v -e "^[[:space:]]*#" -e "^[[:space:]]*$" <<EOF | tee paths-ignore.txt
+        ${{ inputs.paths-ignore }}
+        EOF
+
+        if [[ "${{ github.event_name }}" == 'push' ]]; then
+          LogshInfo "${{ github.event_name }} event"
+          before="${{ inputs.before }}"
+          after="${{ inputs.after }}"
+        elif [[ "${{ github.event_name }}" == 'pull_request' ]]; then
+          LogshInfo "${{ github.event_name }} event"
+          before="${{ inputs.base-ref }}"
+          after="${{ inputs.head-ref }}"
+        else
+          LogshInfo "${{ github.event_name }} event. NOT SKIP."
+          exit 0
+        fi
+
+        if [[ -n "${{ inputs.paths-ignore }}" ]]; then
+          if ! diff_files=$(git diff --name-only "${before:?}" "${after:?}"); then
+            LogshWarn "Failed to get diff files. NOT SKIP."
+            exit 0
+          fi
+          if [[ -z "$(echo "${diff_files:?}" | grep -Ev -f paths-ignore.txt)" ]]; then
+            LogshInfo "Skip the following steps"
+            LogshExec echo "skip=true" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+        else
+          LogshInfo "paths-ignore is empty"
+          if ! diff_files=$(git diff --name-only "${before:?}" "${after:?}"); then
+            LogshWarn "Failed to get diff files. NOT SKIP."
+            exit 0
+          fi
+          if [[ -z "$(echo "${diff_files:?}")" ]]; then
+            LogshInfo "Skip the following steps"
+            LogshExec echo "skip=true" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+        fi
     - name: DEBUG
-      if: ${{ inputs.debug == 'true' }}
+      if: a;ways() && ${{ inputs.debug == 'true' }}
       shell: bash
       run: |
         cat <<'DEBUG_DOC'
@@ -72,75 +155,3 @@ runs:
         ${{ toJSON(github) }}
         ================================================================
         DEBUG_DOC
-    - name: 'github-actions-paths-ignore-alternative'
-      id: paths-ignore
-      shell: 'bash'
-      run: |
-        # LICENSE: https://github.com/kunitsucom/log.sh/blob/HEAD/LICENSE
-        # Common
-        if [ "${LOGSH_COLOR:-}" ] || [ -t 2 ]; then LOGSH_COLOR=true; else LOGSH_COLOR=''; fi
-        _logshRFC3339() { date "+%Y-%m-%dT%H:%M:%S%z" | sed "s/\(..\)$/:\1/"; }
-        _logshCmd() { for a in "$@"; do if echo "${a:-}" | grep -Eq "[[:blank:]]"; then printf "'%s' " "${a:-}"; else printf "%s " "${a:-}"; fi; done | sed "s/ $//"; }
-        # Color
-        LogshDefault() { test "  ${LOGSH_LEVEL:-0}" -gt 000 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;35m}  DEFAULT${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshDebug() { test "    ${LOGSH_LEVEL:-0}" -gt 100 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;34m}    DEBUG${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshInfo() { test "     ${LOGSH_LEVEL:-0}" -gt 200 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;32m}     INFO${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshNotice() { test "   ${LOGSH_LEVEL:-0}" -gt 300 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;36m}   NOTICE${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshWarn() { test "     ${LOGSH_LEVEL:-0}" -gt 400 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;33m}     WARN${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshWarning() { test "  ${LOGSH_LEVEL:-0}" -gt 400 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;33m}  WARNING${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshError() { test "    ${LOGSH_LEVEL:-0}" -gt 500 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;31m}    ERROR${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshCritical() { test " ${LOGSH_LEVEL:-0}" -gt 600 || echo "$*" | awk "{print \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;1;31m} CRITICAL${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshAlert() { test "    ${LOGSH_LEVEL:-0}" -gt 700 || echo "$*" | awk "{print   \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;41m}    ALERT${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshEmergency() { test "${LOGSH_LEVEL:-0}" -gt 800 || echo "$*" | awk "{print \"$(_logshRFC3339) [${LOGSH_COLOR:+\\033[0;1;41m}EMERGENCY${LOGSH_COLOR:+\\033[0m}] \"\$0\"\"}" 1>&2; }
-        LogshExec() { LogshInfo "$ $(_logshCmd "$@")" && "$@"; }
-        LogshRun() { _dlm="####R#E#C#D#E#L#I#M#I#T#E#R####" && _all=$({ _out=$("$@") && _rtn=$? || _rtn=$? && printf "\n%s" "${_dlm:?}${_out:-}" && return "${_rtn:-0}"; } 2>&1) && _rtn=$? || _rtn=$? && _dlmno=$(echo "${_all:-}" | sed -n "/${_dlm:?}/=") && _cmd=$(_logshCmd "$@") && _stdout=$(echo "${_all:-}" | tail -n +"${_dlmno:-1}" | sed "s/^${_dlm:?}//") && _stderr=$(echo "${_all:-}" | head -n "${_dlmno:-1}" | grep -v "^${_dlm:?}") && LogshInfo "$ ${_cmd:-}" && LogshInfo "${_stdout:-}" && { [ -z "${_stderr:-}" ] || LogshWarning "${_stderr:?}"; } && return "${_rtn:-0}"; }
-
-        #
-        # debug
-        #
-        LogshInfo "before: ${{ inputs.before }}"
-        LogshInfo "after: ${{ inputs.after }}"
-        LogshInfo "base-ref: ${{ inputs.base-ref }}"
-        LogshInfo "head-ref: ${{ inputs.head-ref }}"
-
-        #
-        # main
-        #
-        LogshInfo "Create paths-ignore.txt"
-        tee paths-ignore.txt <<EOF
-        ${{ inputs.paths-ignore }}
-        EOF
-
-        if [[ "${{ github.event_name }}" == 'push' ]]; then
-          LogshInfo "push event"
-          before="${{ inputs.before }}"
-          after="${{ inputs.after }}"
-        elif [[ "${{ github.event_name }}" == 'pull_request' ]]; then
-          LogshInfo "pull_request event"
-          before="${{ inputs.base-ref }}"
-          after="${{ inputs.head-ref }}"
-        else
-          LogshInfo "Unsupported event"
-          exit 0
-        fi
-
-        if [[ -n "${{ inputs.paths-ignore }}" ]]; then
-          if ! diff_files=$(git diff --name-only "${before:?}" "${after:?}"); then
-            LogshWarn "Failed to get diff files. NOT SKIP."
-            exit 0
-          fi
-          if [[ -z "$(echo "${diff_files:?}" | grep -v -f paths-ignore.txt)" ]]; then
-            LogshInfo "Skip the following steps"
-            LogshExec echo "skip=true" >> $GITHUB_OUTPUT
-          fi
-        else
-          LogshInfo "paths-ignore is empty"
-          if ! diff_files=$(git diff --name-only "${before:?}" "${after:?}"); then
-            LogshWarn "Failed to get diff files. NOT SKIP."
-            exit 0
-          fi
-          if [[ -z "$(echo "${diff_files:?}")" ]]; then
-            LogshInfo "Skip the following steps"
-            LogshExec echo "skip=true" >> $GITHUB_OUTPUT
-          fi
-        fi
